// webpack/vue/assets/js/homepage/components/Filters.vue
<script>
  export default {
    name: 'Filters',
    props: {
      nameFilter: {
        type: String,
        required: true,
      },
    },
    methods: {
      onNameFilterInput(e) {
        this.$emit('name-filter-change', e.target.value);
      },
    },
  };
</script>

<template>
    <div>
        <label for="nameFilter">Rechercher un joueur :</label>
        <input
            id="nameFilter"
            type="text"
            class="border border-gray-400 rounded py-1 px-2 m-2 focus:shadow-inner"
            :value="nameFilter"
            @input="onNameFilterInput"
        >
    </div>
</template>

// webpack/react/assets/js/homepage/components/Filters.jsx
import React from 'react';
import PropTypes from 'prop-types';

export default function Filters(props) {
  const { nameFilter, setNameFilter } = props;

  function handleNameFilterChange(e) {
    setNameFilter(e.target.value);
  }

  return (
    <div>
      <label htmlFor="nameFilter">Rechercher un joueur :</label>
      {''}
      <input id="nameFilter" type="text" className="border border-gray-400 rounded py-1 px-2 m-2 focus:shadow-inner" value={nameFilter} onChange={handleNameFilterChange} />
    </div>
  );
}

Filters.propTypes = {
  nameFilter: PropTypes.string.isRequired,
  setNameFilter: PropTypes.func.isRequired,
};
