// webpack/vue/assets/js/homepage/components/TopPersons.vue
<script>
  import TopPerson from './TopPerson';

  export default {

    name: 'TopPersons',
    components: {
      TopPerson,
    },
    props: {
      topPersons: {
        type: Array,
        required: true,
      },
      isLoading: {
        type: Boolean,
        required: true,
      },
    },
  };
</script>

<template>
    <div>
        <div
            v-if="isLoading"
            class="text-center py-2"
        >
            Chargement...
        </div>
        <div v-else class="flex flex-row flex-wrap -mx-2">
            <div
                v-for="(topPerson) in topPersons"
                :key="topPerson.personId"
                class="w-1/5 p-2"
            >
                <TopPerson :top-person="topPerson" />
            </div>
        </div>
    </div>
</template>

// webpack/react/assets/js/homepage/components/TopPersons.jsx
import React from 'react';
import PropTypes from 'prop-types';
import TopPerson from './TopPerson';

export default function TopPersons(props) {
  const { topPersons, isLoading } = props;

  return (
    <div>
      {true === isLoading ? (
        <div className="text-center py-2">Chargement...</div>
      ) : (
        <div className="flex flex-row flex-wrap -mx-2">
          {topPersons.map((topPerson) => (
            <div key={topPerson.personId} className="w-1/5 p-2">
              <TopPerson topPerson={topPerson} />
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

TopPersons.propTypes = {
  topPersons: PropTypes.arrayOf(PropTypes.shape({
    personId: PropTypes.string.isRequired,
  })).isRequired,
  isLoading: PropTypes.bool.isRequired,
};
