// webpack/react/assets/js/homepage/components/TopPerson.jsx
import React from 'react';
import PropTypes from 'prop-types';
import Card from '../../components/Card';

export default function TopPerson(props) {
  const { topPerson } = props;

  return (
    <Card title={topPerson.personName} className={topPerson.isWinner ? 'bg-green-200' : ''}>
      <div className="font-bold text-xl mb-2">
        {topPerson.personName}
        {topPerson.isWinner && <i className="fas fa-crown float-right" />}
      </div>
      <div>
        <strong>Rang moyen :</strong>
        {' '}
        #
        {(null !== topPerson.averageRank) ? topPerson.averageRank : '?'}
      </div>
      <div className="mt-2">
        <strong>Nombre de parties :</strong>
        {' '}
        {topPerson.gameCount}
      </div>
      <div className="mt-2">
        <strong>Nombre de victoires :</strong>
        {' '}
        {topPerson.victoryCount}
      </div>
    </Card>
  );
}

TopPerson.propTypes = {
  topPerson: PropTypes.shape({
    personName: PropTypes.string.isRequired,
    gameCount: PropTypes.number.isRequired,
    averageRank: PropTypes.oneOfType([
      PropTypes.number,
      PropTypes.oneOf([null]),
    ]),
    victoryCount: PropTypes.number.isRequired,
    isWinner: PropTypes.bool,
  }).isRequired,
};

// webpack/vue/assets/js/homepage/components/TopPerson.vue
<script>
  export default {
    name: 'TopPerson',
    props: {
      topPerson: {
        type: Object,
        required: true,
      },
    },
  };
</script>

<template>
    <Card :class="{'bg-green-200': topPerson.isWinner}">
        <div class="font-bold text-xl mb-2">
            {{ topPerson.personName }}
            <i v-if="topPerson.isWinner" class="fas fa-crown float-right" />
        </div>
        <div>
            <strong>Rang moyen :</strong>
            #{{ (null !== topPerson.averageRank) ? topPerson.averageRank : '?' }}
        </div>
        <div class="mt-2">
            <strong>Nombre de parties :</strong>
            {{ topPerson.gameCount }}
        </div>
        <div class="mt-2">
            <strong>Nombre de victoires :</strong>
            {{ topPerson.victoryCount }}
        </div>
    </Card>
</template>
